### ISSUE TITLE
Will be the new release?

### ISSUE THREAD

**Issue by biapar** [xamarin/xamarin-forms-book-preview-2#19]
Will be the new release?

**Comment by charlespetzold** [comment]
The 2nd preview of the book was superseded by the 1st edition. Here's the page for the 1st edition of the book:

https://developer.xamarin.com/guides/xamarin-forms/creating-mobile-apps-xamarin-forms/

Here's the GitHub repo with the code for the 1st edition:

https://github.com/xamarin/xamarin-forms-book-samples

There are currently no plans for a 2nd edition. Instead, much information on Xamarin.Forms can be found on the website:

https://developer.xamarin.com/guides/#xamarin-forms
