### ISSUE TITLE
Chapters 4 & 9 header texts

### ISSUE THREAD

**Issue by almata** [xamarin/xamarin-forms-book-preview-2#4]
Both in chapters 4 and 9, the texts at the top of each page, where it says something like _Chapter N. Actual Title of that Chapter_ are wrong (they belong to other chapters).

Also, in page 77 (that's chapter 4), there's a period missing at the end of third paragraph.

**Comment by charlespetzold** [comment]
Fixed! Thanks.

**Comment by charlespetzold** [comment]
Fixed in underlying files. Thanks!
